### ISSUE TITLE
How to filter already filter list on another column

### ISSUE THREAD

**Issue by Jerome2606** [DeuxHuitHuit/quicksearch#14] opened 2015-02-20 14:38 UTC
Hi,

I use this testquery:
```javascript
    $(this).quicksearch("[id*=grvPointDeVente] tr:not(:has(th))", {
                     'testQuery': function (query, txt, row) {
                         //:eq = Select the element at index n within the matched set.
                         return $(row).children(":eq(" + i + ")").text().toLowerCase().indexOf(query[0].toLowerCase()) != -1
                             || ($(row).children(":eq(" + i + ")").find('input[type=checkbox]') != undefined ?
                                     $(row).children(":eq(" + i + ")").find('input[type=checkbox]').prop('checked') == query[0].toLowerCase() :
                                     false);
                     }
                 });
```

When I filter on one column, it's works.
But when I add another filter on another column the previous filter is ignored.

Example:
I want to see the users who lives in Namur and have a specific Name.
So I put 5000 in postalCode column and X in Name. But only the last filled filter is used.

Thanks

**Comment by nitriques** [comment] 2015-02-20 15:08
Yeah that's normal. quicksearch itself only uses one filter type.

Look at the prepareQuery option, maybe it could help you to merge multiple filters in the regexp.

BTW you should avoid any jQuery calls in the testQuey since it will be a penalty cost. Use the given parameters.

I'll close the issue since it's not a bug.

**Closed by nitriques** 2015-02-20 15:08 UTC
